### ISSUE TITLE
增加了一个免驱的无线网卡，plist要修改什么吗

### ISSUE THREAD

**Issue by foisu** [leogcry22/iHac-Pro#1]
bcm94360cd的一个无线网卡，逻辑上免驱，应该可以引导啊，但是引导到IOUSBHost Interface部分就炸了

**Comment by leogcry22** [comment]
不确定是不是：https://imacos.top/2019/10/22/1427/ 中提到的问题，可以参考一下。我手里暂时没有网卡，下个月应该会搞一块来看看

**Comment by foisu** [comment]
应该是usb定制的问题吧，我目前的解决办法是，增加USBInjectAll.kext 这个，同时把usb定制的2个先关掉，目前系统已经装好，稍后研究下定制，猜测是不是只要把主板上前置的usb2.0 接口1加入到定制里面就好了。

**Comment by foisu** [comment]
头痛 装好了发掘网卡拿不到 ip地址，诡异的事情了，明天重新在折腾一次10.15.3试试看

**Comment by leogcry22** [comment]
我这边重新定制了USB，不知道能不能解决你的问题
